name: auto merge deploy
on:
  pull_request:
    types: [closed]

jobs:
  auto-merge-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.auto_merge != null
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/deploy.yml
