name: deploy
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Start deploy"
      - run: |
          echo "deploy these files:"
          ls
      - run: sleep 10
      - run: echo "Complete deploy"
