name: notify deployment failed
on:
  workflow_run:
    types: [completed]
    workflows: 
      - some long test

jobs:
  notify-deployment-faield:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.workflow_run.conclusion == 'failure'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          PR_URI="/repos/${{ github.event.repository.full_name }}/pulls/${{ github.event.workflow_run.pull_requests[0].number }}"
          if (gh api "${PR_URI}" | jq --exit-status .auto_merge > /dev/null); then
            echo -e "CIが失敗したためリリースを中断します"
          fi
