name: notify deployment start
on:
  pull_request:
    types: [auto_merge_enabled]

jobs:
  notify-deployment-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "CI回ったらリリースします by ${{ github.event.sender.display_login }}\n[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})"
