name: notify deployment failed
on:
  check_suite:
    types: [completed]

jobs:
  notify-deployment-faield:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    #if: github.event.check_suite.conclusion != "success"
    steps:
      - run: |
          PR_URI="/repos/${{ github.event.repository.full_name }}/pulls/${{ github.event.check_suite.pull_requests[0].number }}"
          if [[ gh api $PR_URI | jq --exit-status .auto_merge > /dev/null  ]]; then
            echo -e "CIが失敗したためリリースを中断します\n[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})"
          fi
